SHAREDDIR=/usr/local/share/gyach
BINDIR=/usr/local/bin


all: inst

#build package
inst:
	if test -f COMPILE-ME.sh; then\
		./COMPILE-ME.sh; \
	fi;



#install mo files
install: 
	if test -f INSTALL-ME.sh; then\
		./INSTALL-ME.sh; \
	fi;